/**
 * @fileoverview Compiling quartet into something you can hand somebody.
 *
 * One executable per platform, and two ways to get it: a file attached to a GitHub release
 * that `install.sh` fetches, and an npm package whose per-platform dependency carries the
 * same bytes. Both come from this script, and the release workflow builds the binary once and
 * feeds it to both — a macOS binary is ad-hoc signed by the machine that compiled it, and
 * rebuilding it elsewhere would throw that signature away.
 *
 * The one subtlety is the app. `Bun.build` can only embed a file it can see a static import
 * for, and Vite's output filenames are content-hashed, so they are not knowable until the app
 * has been built. So the app is built first, a module of imports is generated from what
 * landed on disk, and a plugin substitutes it for `packages/bridge/src/embedded-app.ts` —
 * which is empty in a checkout, where there is a real `dist` to read instead.
 */

import { mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { copyFileSync, chmodSync } from "node:fs";
import { existsSync } from "node:fs";
import { join, sep } from "node:path";
import { assertPublishable, currentVersion, type ResolvedVersion } from "./version";

const ROOT = new URL("..", import.meta.url).pathname;
const PACKAGES = join(ROOT, "packages");
const BUILT_APP_DIRECTORY = join(PACKAGES, "app", "dist");
const GENERATED_APP_MODULE = join(ROOT, ".build", "embedded-app.generated.ts");
const GENERATED_VERSION_MODULE = join(ROOT, ".build", "embedded-version.generated.ts");
const ENTRYPOINT = join(PACKAGES, "cli", "src", "main.ts");

/**
 * Release targets, from Bun's target triple to the name the install script looks for.
 *
 * Windows is deliberately absent: `install.sh` is POSIX-only, the bridge writes its identity
 * files with POSIX permissions it then checks, and neither has ever been exercised there.
 * Musl gets its own asset because Bun's glibc binaries do not run on Alpine.
 */
const COMPILE_TARGETS: Readonly<Partial<Record<Bun.Build.CompileTarget, string>>> = {
  "bun-darwin-arm64": "quartet-darwin-arm64",
  "bun-darwin-x64": "quartet-darwin-x64",
  "bun-linux-arm64": "quartet-linux-arm64",
  "bun-linux-x64": "quartet-linux-x64",
  "bun-linux-arm64-musl": "quartet-linux-arm64-musl",
  "bun-linux-x64-musl": "quartet-linux-x64-musl",
};

/**
 * The same targets, mapped to the npm package that carries each platform's binary as an
 * optionalDependency of `quartet-ai` (see `deploy/npm/`). One binary, two channels; this only
 * names where the compiled output goes for the second one.
 */
const NPM_PLATFORM_PACKAGES: Readonly<Partial<Record<Bun.Build.CompileTarget, string>>> = {
  "bun-darwin-arm64": "quartet-ai-darwin-arm64",
  "bun-darwin-x64": "quartet-ai-darwin-x64",
  "bun-linux-arm64": "quartet-ai-linux-arm64",
  "bun-linux-x64": "quartet-ai-linux-x64",
  "bun-linux-arm64-musl": "quartet-ai-linux-arm64-musl",
  "bun-linux-x64-musl": "quartet-ai-linux-x64-musl",
};

function isKnownCompileTarget(target: string): target is Bun.Build.CompileTarget {
  return Object.hasOwn(COMPILE_TARGETS, target);
}

/** Builds the app, because a binary with no app in it serves the "no build found" notice. */
async function buildApp(): Promise<void> {
  const result = Bun.spawnSync(["bun", "run", "build"], {
    cwd: join(PACKAGES, "app"),
    stdout: "inherit",
    stderr: "inherit",
  });
  if (result.exitCode !== 0) throw new Error("The app build failed; the binary would be empty.");
}

/**
 * Writes the module that carries the built app into the binary.
 *
 * Each file becomes a `{ type: "file" }` import, which Bun copies into the executable and
 * resolves at runtime to a path inside its embedded filesystem. The table is keyed by the URL
 * the browser asks for, because that is the only question the server ever asks of it.
 */
function generateEmbeddedAppModule(): string {
  const files = [...new Bun.Glob("**/*").scanSync({ cwd: BUILT_APP_DIRECTORY, onlyFiles: true })]
    .map((entry) => entry.split(sep).join("/"))
    .sort();

  if (!files.includes("index.html")) {
    throw new Error(
      `No index.html in ${BUILT_APP_DIRECTORY} — the app build did not produce a shell.`,
    );
  }

  const imports = files.map(
    (file, index) =>
      `import file${String(index)} from "../packages/app/dist/${file}" with { type: "file" };`,
  );
  const entries = files.map(
    (file, index) => `  ${JSON.stringify(`/${file}`)}: file${String(index)},`,
  );

  // The type is repeated rather than imported: this module replaces embedded-app.ts, so
  // importing from there would resolve straight back to this file.
  const contents = [
    "// Generated by scripts/build.ts. Do not edit.",
    "",
    ...imports,
    "",
    "export const EMBEDDED_APP_FILES: Readonly<Record<string, string>> | undefined = {",
    ...entries,
    "};",
    "",
  ].join("\n");

  mkdirSync(join(ROOT, ".build"), { recursive: true });
  writeFileSync(GENERATED_APP_MODULE, contents);
  process.stdout.write(`  embedded ${String(files.length)} app files\n`);
  return GENERATED_APP_MODULE;
}

/**
 * Writes the module carrying the version into the binary.
 *
 * A released `quartet` has no git repository to ask and no manifest beside it, so the tag has
 * to be baked in here, while there is still something that knows it.
 */
function generateEmbeddedVersionModule(version: string): string {
  const contents = [
    "// Generated by scripts/build.ts. Do not edit.",
    "",
    `export const EMBEDDED_VERSION: string | undefined = ${JSON.stringify(version)};`,
    "",
  ].join("\n");
  mkdirSync(join(ROOT, ".build"), { recursive: true });
  writeFileSync(GENERATED_VERSION_MODULE, contents);
  return GENERATED_VERSION_MODULE;
}

/**
 * Swaps each checkout-only module for the generated one that has the answer.
 *
 * Both are empty in a checkout on purpose: there, the app is a real directory and the version
 * is a question for git. Only a compile needs them filled in.
 */
function embedPlugin(generated: Readonly<Record<string, string>>): import("bun").BunPlugin {
  return {
    name: "quartet-embedded",
    setup(build) {
      build.onResolve({ filter: /^\.\/embedded-(app|version)$/ }, (args) => {
        const path = generated[args.path];
        if (path === undefined) throw new Error(`Nothing generated for ${args.path}`);
        return { path };
      });
    },
  };
}

/**
 * Compiles one self-contained binary, app and all.
 *
 * @param compileTarget - A Bun target triple from {@link COMPILE_TARGETS}.
 * @returns Path to the compiled binary.
 */
async function buildStandaloneBinary(
  compileTarget: string,
  generated: Readonly<Record<string, string>>,
): Promise<string> {
  if (!isKnownCompileTarget(compileTarget)) {
    throw new Error(
      `Unknown target "${compileTarget}". Known targets: ${Object.keys(COMPILE_TARGETS).join(", ")}`,
    );
  }

  const outputName = COMPILE_TARGETS[compileTarget] as string;
  const outfile = join(ROOT, "deploy", "binaries", outputName);

  const result = await Bun.build({
    entrypoints: [ENTRYPOINT],
    target: "bun",
    minify: true,
    plugins: [embedPlugin(generated)],
    compile: { target: compileTarget, outfile },
  });

  if (!result.success) {
    for (const message of result.logs) process.stderr.write(`${String(message)}\n`);
    throw new Error(`Compile failed for ${compileTarget}`);
  }

  const megabytes = (statSync(outfile).size / 1024 / 1024).toFixed(1);
  process.stdout.write(`  ${outputName}  ${megabytes} MB\n`);
  return outfile;
}

/**
 * Copies a compiled binary into its npm platform package and stamps that package's version to
 * match the root manifest, so `npm publish` from that directory ships exactly this binary at
 * exactly this version.
 */
function stageNpmPlatformPackage(compileTarget: string, binaryPath: string, version: string): void {
  const packageName = NPM_PLATFORM_PACKAGES[compileTarget as Bun.Build.CompileTarget];
  if (packageName === undefined) {
    throw new Error(`No npm platform package mapped for target "${compileTarget}".`);
  }

  const packageDir = join(ROOT, "deploy", "npm", packageName);
  const binDir = join(packageDir, "bin");
  mkdirSync(binDir, { recursive: true });
  copyFileSync(binaryPath, join(binDir, "quartet"));
  chmodSync(join(binDir, "quartet"), 0o755);

  const packageJsonPath = join(packageDir, "package.json");
  const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf8")) as Record<string, unknown>;
  packageJson["version"] = version;
  writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\n`);

  process.stdout.write(`  staged ${packageName}@${version}\n`);
}

/**
 * Stamps `deploy/npm/quartet-ai`'s version and its optionalDependencies to match the root
 * manifest, and copies in the docs its `files` list references. This package never contains a
 * binary: that ships only inside the platform packages it depends on.
 */
function stageNpmMainPackage(version: string): void {
  const packageDir = join(ROOT, "deploy", "npm", "quartet-ai");
  const packageJsonPath = join(packageDir, "package.json");
  const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf8")) as {
    version: string;
    optionalDependencies: Record<string, string>;
    [key: string]: unknown;
  };

  packageJson.version = version;
  for (const dependency of Object.keys(packageJson.optionalDependencies)) {
    packageJson.optionalDependencies[dependency] = version;
  }
  writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\n`);

  copyFileSync(join(ROOT, "README.md"), join(packageDir, "README.md"));
  copyFileSync(join(ROOT, "LICENSE"), join(packageDir, "LICENSE"));

  process.stdout.write(`  staged quartet-ai@${version}\n`);
}

/**
 * Stages every npm platform package from binaries already on disk, skipping the compile.
 *
 * Lets the publish job reuse the macOS-signed binaries the build job produced rather than
 * rebuilding unsigned copies: an ad-hoc signature only applies on the OS that made it, and an
 * unsigned Mach-O is killed on sight by arm64 macOS.
 */
function stageNpmPackagesFromExistingBinaries(binariesDir: string, resolved: ResolvedVersion): void {
  assertPublishable(resolved);
  for (const target of Object.keys(COMPILE_TARGETS)) {
    const outputName = COMPILE_TARGETS[target as Bun.Build.CompileTarget] as string;
    const binaryPath = join(binariesDir, outputName);
    if (!existsSync(binaryPath)) {
      throw new Error(`Expected a binary at ${binaryPath} — was it downloaded and unpacked first?`);
    }
    stageNpmPlatformPackage(target, binaryPath, resolved.version);
  }
  stageNpmMainPackage(resolved.version);
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const resolved = currentVersion(args);

  const fromDirIndex = args.indexOf("--npm-packages-from-dir");
  if (fromDirIndex !== -1) {
    const binariesDir = args[fromDirIndex + 1];
    if (binariesDir === undefined) {
      throw new Error("--npm-packages-from-dir requires a directory argument.");
    }
    stageNpmPackagesFromExistingBinaries(binariesDir, resolved);
    return;
  }

  const explicitTargets = args
    .flatMap((arg, index) => (arg === "--target" ? [args[index + 1]] : []))
    .filter((target): target is string => target !== undefined);

  const targets = args.includes("--all-targets")
    ? Object.keys(COMPILE_TARGETS)
    : explicitTargets.length > 0
      ? explicitTargets
      : [`bun-${process.platform}-${process.arch}`];

  // Once, not per target: the app is the same bytes on every platform, and rebuilding it six
  // times would only give six chances for the hashes to disagree.
  if (!args.includes("--skip-app-build")) await buildApp();
  const generated = {
    "./embedded-app": generateEmbeddedAppModule(),
    "./embedded-version": generateEmbeddedVersionModule(resolved.version),
  };
  process.stdout.write(`  version ${resolved.version} (${resolved.source})\n`);

  const stageNpm = args.includes("--npm-packages");
  // Before compiling six binaries, not after: an untagged release should fail in a second
  // rather than three minutes in, with the staging step as the thing that noticed.
  if (stageNpm) assertPublishable(resolved);
  mkdirSync(join(ROOT, "deploy", "binaries"), { recursive: true });
  for (const target of targets) {
    const binaryPath = await buildStandaloneBinary(target, generated);
    if (stageNpm) stageNpmPlatformPackage(target, binaryPath, resolved.version);
  }

  if (stageNpm) stageNpmMainPackage(resolved.version);
}

await main();
